import { Box } from '@/components/Box'
import { BoxTitle } from '@/components/BoxTitle'
import { PressKeys } from '@/components/PressKeys'
import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Event Key</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PressKeys/>
    </>
  )
}
